export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Events } from "./Events";
export { default as Products } from "./Products";
export { default as Contact } from "./Contact";
export { default as Location } from "./Location";
export { default as History } from "./History";
export { default as Gallery } from "./Gallery";
export { default as Blog } from "./Blog";
